# Generated by Django 5.0.2 on 2024-02-23 13:21

import django.contrib.auth.validators
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=64,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="Логин",
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=64, verbose_name="Имя"),
                ),
                (
                    "surname",
                    models.CharField(blank=True, max_length=64, verbose_name="Фамилия"),
                ),
                (
                    "patronymic",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Отчество"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=64, verbose_name="Электронная почта"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("VIEWER", "viewer"), ("ADMIN", "admin")],
                        default="VIEWER",
                        max_length=64,
                        verbose_name="Роль",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
            ],
            options={
                "abstract": False,
            },
            managers=[
                ("objects", users.models.UserManager()),
            ],
        ),
    ]
