# Generated by Django 5.0.2 on 2024-04-30 07:08

import django.contrib.auth.validators
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=64,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="Логин пользователя",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Имя пользователя"
                    ),
                ),
                (
                    "surname",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Фамилия пользователя"
                    ),
                ),
                (
                    "patronymic",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Отчество пользователя"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=64,
                        verbose_name="Электронная почта пользователя",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("VIEWER", "Зритель"),
                            ("SPECIALIST", "Специалист"),
                            ("ADMIN", "Администратор"),
                        ],
                        default="VIEWER",
                        max_length=64,
                        verbose_name="Роль пользователя",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
                "ordering": ("role", "id"),
            },
            managers=[
                ("objects", users.models.UserManager()),
            ],
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                fields=("username", "email"), name="unique_username_email"
            ),
        ),
    ]
