# Generated by Django 5.0.2 on 2024-02-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("VIEWER", "Зритель"),
                    ("SPECIALIST", "Специалист"),
                    ("ADMIN", "Администратор"),
                ],
                default="VIEWER",
                max_length=64,
                verbose_name="Роль",
            ),
        ),
    ]
