# Generated by Django 5.0.2 on 2024-05-13 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logs", "0015_alter_notificationtype_method"),
        ("users", "0002_user_phone_number_alter_user_email_alter_user_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("VIEWER", "Наблюдатель"),
                    ("SPECIALIST", "Специалист"),
                    ("ADMIN", "Администратор"),
                ],
                default="VIEWER",
                max_length=64,
                verbose_name="Роль пользователя",
            ),
        ),
        migrations.CreateModel(
            name="UserNotificationType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notification_type_users",
                        to="logs.notificationtype",
                        verbose_name="Тип оповещения, которые получает пользователь",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_notification_types",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь, получающий оповещения",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="notification_types",
            field=models.ManyToManyField(
                related_name="users",
                through="users.UserNotificationType",
                to="logs.notificationtype",
                verbose_name="Типы оповещений",
            ),
        ),
    ]
