# Generated by Django 5.0.2 on 2024-02-27 15:46

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_options_user_unique_username_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True, max_length=64, verbose_name="Электронная почта пользователя"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(
                blank=True, max_length=64, verbose_name="Имя пользователя"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="patronymic",
            field=models.CharField(
                blank=True, max_length=64, verbose_name="Отчество пользователя"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("VIEWER", "Зритель"),
                    ("SPECIALIST", "Специалист"),
                    ("ADMIN", "Администратор"),
                ],
                default="VIEWER",
                max_length=64,
                verbose_name="Роль пользователя",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="surname",
            field=models.CharField(
                blank=True, max_length=64, verbose_name="Фамилия пользователя"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                max_length=64,
                unique=True,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                verbose_name="Логин пользователя",
            ),
        ),
    ]
