# Generated by Django 5.0.2 on 2024-04-30 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LogFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название лог-файла"),
                ),
                (
                    "path",
                    models.CharField(max_length=255, verbose_name="Путь до лог-файла"),
                ),
                (
                    "last_positions",
                    models.IntegerField(
                        default=0, verbose_name="Последняя позиция при чтении"
                    ),
                ),
            ],
            options={
                "verbose_name": "Лог-файл",
                "verbose_name_plural": "Лог-файлы",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="LogFileType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=64, verbose_name="Название типа лог-файла"
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип лог-файла",
                "verbose_name_plural": "Типы лог-файла",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="AnomalousLogEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        max_length=255, verbose_name="Текст события лог-файла"
                    ),
                ),
                (
                    "datetime",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время события лог-файла"
                    ),
                ),
                (
                    "log_file",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="anomalous_log_events",
                        to="logs.logfile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Аномальное событие лог-файла",
                "verbose_name_plural": "Аномальные события лог-файла",
                "ordering": ("datetime",),
            },
        ),
        migrations.AddField(
            model_name="logfile",
            name="type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="log_files",
                to="logs.logfiletype",
            ),
        ),
        migrations.CreateModel(
            name="SearchPattern",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pattern",
                    models.CharField(max_length=255, verbose_name="Поисковый паттерн"),
                ),
                (
                    "type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="search_patterns",
                        to="logs.logfiletype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Поисковый паттерн",
                "verbose_name_plural": "Поисковые паттерны",
                "ordering": ("id",),
            },
        ),
    ]
