# Generated by Django 5.0.2 on 2024-02-27 15:46

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LogFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название лог-файла"),
                ),
                (
                    "path",
                    models.CharField(max_length=255, verbose_name="Путь до лог-файла"),
                ),
            ],
            options={
                "verbose_name": "Лог-файл",
                "verbose_name_plural": "Лог-файлы",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="LogFileType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=64, verbose_name="Название типа лог-файла"
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип лог-файла",
                "verbose_name_plural": "Типы лог-файла",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="AnomalousLogEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        max_length=255, verbose_name="Текст события лог-файла"
                    ),
                ),
                (
                    "datetime",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2024,
                            2,
                            27,
                            15,
                            46,
                            40,
                            738810,
                            tzinfo=datetime.timezone.utc,
                        ),
                        verbose_name="Дата и время события лог-файла",
                    ),
                ),
                (
                    "log_file",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="anomalous_log_events",
                        to="logs.logfile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Аномальное событие лог-файла",
                "verbose_name_plural": "Аномальные события лог-файла",
                "ordering": ("datetime",),
            },
        ),
        migrations.AddField(
            model_name="logfile",
            name="type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="log_files",
                to="logs.logfiletype",
            ),
        ),
    ]
