# Generated by Django 5.0.2 on 2024-04-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchpattern",
            name="regex",
            field=models.BooleanField(
                default=False, verbose_name="Регулярное выражение"
            ),
        ),
    ]
