# Generated by Django 5.0.2 on 2024-03-10 08:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logs", "0002_alter_anomalouslogevent_datetime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anomalouslogevent",
            name="datetime",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 10, 8, 19, 2, 279384, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Дата и время события лог-файла",
            ),
        ),
    ]
