# Generated by Django 5.0.2 on 2024-04-30 15:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("logs", "0002_searchpattern_regex"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AnomalousLogEvent",
            new_name="AnomalousEvent",
        ),
        migrations.RenameModel(
            old_name="LogFileType",
            new_name="LogType",
        ),
    ]
