# Generated by Django 5.0.2 on 2024-05-04 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logs", "0003_rename_anomalouslogevent_anomalousevent_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="logtype",
            options={
                "ordering": ("name",),
                "verbose_name": "Тип протокола / ПО лог-файла",
                "verbose_name_plural": "Типы протоколов / ПО лог-файла",
            },
        ),
        migrations.RemoveField(
            model_name="searchpattern",
            name="type",
        ),
        migrations.AlterField(
            model_name="logtype",
            name="name",
            field=models.CharField(
                max_length=64, verbose_name="Название типа протокола / ПО лог-файла"
            ),
        ),
        migrations.CreateModel(
            name="LogTypeSearchPattern",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "log_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="log_type_search_patterns",
                        to="logs.logtype",
                    ),
                ),
                (
                    "search_pattern",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="search_pattern_log_types",
                        to="logs.searchpattern",
                    ),
                ),
            ],
            options={
                "verbose_name": "Связь типа протокола / ПО и поискового паттерна",
                "verbose_name_plural": "Связи типов протокола / ПО и поисковых паттернов",
                "ordering": ("id",),
            },
        ),
    ]
