# Generated by Django 5.0.2 on 2024-03-10 09:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logs", "0004_logfile_last_positions_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anomalouslogevent",
            name="datetime",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 10, 9, 22, 2, 588671, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Дата и время события лог-файла",
            ),
        ),
    ]
