# Generated by Django 5.0.2 on 2024-05-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logs", "0005_logtype_search_patterns"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="searchpattern",
            name="regex",
        ),
        migrations.AddField(
            model_name="searchpattern",
            name="search_type",
            field=models.CharField(
                choices=[
                    ("SIMPLE", "По полному вхождению"),
                    ("REGEX", "Регулярное выражение"),
                    ("COEFFICIENT", "Словарный коэффициент вхождения"),
                ],
                default=1,
                max_length=255,
                verbose_name="Тип поиска",
            ),
            preserve_default=False,
        ),
    ]
