# Generated by Django 5.0.2 on 2024-05-04 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logs", "0006_remove_searchpattern_regex_searchpattern_search_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchpattern",
            name="name",
            field=models.CharField(
                default="test",
                max_length=255,
                verbose_name="Краткое понятное название или описание",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="anomalousevent",
            name="datetime",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата и время"),
        ),
        migrations.AlterField(
            model_name="anomalousevent",
            name="text",
            field=models.CharField(max_length=255, verbose_name="Текст"),
        ),
        migrations.AlterField(
            model_name="logfile",
            name="name",
            field=models.CharField(
                max_length=255, verbose_name="Краткое понятное название или описание"
            ),
        ),
        migrations.AlterField(
            model_name="logfile",
            name="path",
            field=models.CharField(
                max_length=255, verbose_name="Физический путь до файла"
            ),
        ),
        migrations.AlterField(
            model_name="logtype",
            name="name",
            field=models.CharField(
                max_length=255, verbose_name="Краткое понятное название или описание"
            ),
        ),
        migrations.AlterField(
            model_name="logtype",
            name="search_patterns",
            field=models.ManyToManyField(
                related_name="log_types",
                through="logs.LogTypeSearchPattern",
                to="logs.searchpattern",
                verbose_name="Подвязанные поисковые паттерны",
            ),
        ),
    ]
