# Generated by Django 5.0.2 on 2024-05-12 07:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logs", "0011_notificationtype_searchpatternnotificationtype_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notificationtype",
            name="name",
        ),
        migrations.AddField(
            model_name="notificationtype",
            name="description",
            field=models.CharField(
                default=datetime.datetime(2024, 5, 12, 12, 59, 34, 387201),
                max_length=64,
                verbose_name="Описание",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="notificationtype",
            name="method",
            field=models.CharField(
                default=datetime.datetime(2024, 5, 12, 12, 59, 40, 45415),
                max_length=64,
                verbose_name="Метод оповещения",
            ),
            preserve_default=False,
        ),
    ]
