# Generated by Django 5.0.2 on 2024-05-12 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logs", "0012_remove_notificationtype_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="anomalousevent",
            name="detected_search_pattern",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="anomalous_events",
                to="logs.searchpattern",
                verbose_name="Поисковый паттерн, обнаруживший событие",
            ),
        ),
    ]
