# Generated by Django 5.0.2 on 2024-05-12 13:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("logs", "0013_anomalousevent_detected_search_pattern"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="anomalousevent",
            name="detected_search_pattern",
        ),
    ]
