# Generated by Django 5.0.2 on 2024-05-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logs", "0016_searchpattern_coefficient"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchpattern",
            name="count_of_events",
            field=models.IntegerField(
                default=0, null=True, verbose_name="Количество событий до оповещения"
            ),
        ),
        migrations.AddField(
            model_name="searchpattern",
            name="period_of_events",
            field=models.TimeField(
                default=None,
                null=True,
                verbose_name="Период для подсчёта количества событий до оповещения",
            ),
        ),
        migrations.AlterField(
            model_name="searchpattern",
            name="search_type",
            field=models.CharField(
                choices=[
                    ("SIMPLE", "По полному вхождению"),
                    ("REGEX", "Регулярное выражение"),
                    ("COEFFICIENT", "Словарный коэффициент вхождения"),
                    ("COUNTER", "Повторяющееся событие"),
                ],
                max_length=255,
                verbose_name="Тип поиска",
            ),
        ),
    ]
