# Generated by Django 5.0.2 on 2024-05-17 17:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logs", "0018_searchpattern_counter_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="anomalousevent",
            name="count_of_events",
            field=models.IntegerField(
                default=0, verbose_name="Количество событий в рамках периода"
            ),
        ),
    ]
