# Generated by Django 5.0.2 on 2024-05-17 17:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logs", "0019_anomalousevent_count_of_events"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anomalousevent",
            name="count_of_events",
            field=models.IntegerField(
                default=None,
                null=True,
                verbose_name="Количество событий в рамках периода",
            ),
        ),
    ]
