# Generated by Django 5.0.2 on 2024-06-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logs", "0021_alter_anomalousevent_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="searchpattern",
            name="pattern",
            field=models.CharField(max_length=4096, verbose_name="Поисковый паттерн"),
        ),
    ]
