# Generated by Django 5.0.2 on 2024-06-04 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logs", "0022_alter_searchpattern_pattern"),
    ]

    operations = [
        migrations.AddField(
            model_name="anomalousevent",
            name="detected_search_pattern",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="anomalous_events",
                to="logs.searchpattern",
            ),
        ),
        migrations.AlterField(
            model_name="anomalousevent",
            name="log_file",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="anomalous_events",
                to="logs.logfile",
            ),
        ),
    ]
