# Generated by Django 5.0.2 on 2024-06-08 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logs", "0023_anomalousevent_detected_search_pattern_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="logfile",
            name="one_time_scan_is_done",
            field=models.BooleanField(
                default=False, verbose_name="Одноразовое сканирование заверешно"
            ),
        ),
        migrations.AlterField(
            model_name="anomalousevent",
            name="count_of_events",
            field=models.IntegerField(
                default=0, null=True, verbose_name="Количество событий в рамках периода"
            ),
        ),
    ]
